name: Test
on: [push]
jobs:
  test:
    name: Node v${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}

      - name: npm install
        run: npm install

      - name: npm -v && node -v
        run: npm -v && node -v

      - name: npm test
        run: npm test
